### ISSUE TITLE
ignoring return value of 'freopen': all warnings being treated as errors

### ISSUE THREAD

**Issue by ecerulm** [thoughtbot/pick#14]
Hi, 

I tried to compile in the current HEAD on Ubuntu 14.04 and Im getting

```
make  all-recursive
make[1]: Entering directory `/home/ecerulm/tmp/pick'
Making all in src
make[2]: Entering directory `/home/ecerulm/tmp/pick/src'
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -pedantic-errors -Wno-unused-parameter -Werror -g -O2 -MT ui.o -MD -MP -MF .deps/ui.Tpo -c -o ui.o ui.c
ui.c: In function ‘start_curses’:
ui.c:48:9: error: ignoring return value of ‘freopen’, declared with attribute warn_unused_result [-Werror=unused-result]
  freopen("/dev/tty", "r", stdin);
         ^
cc1: all warnings being treated as errors
make[2]: *** [ui.o] Error 1
make[2]: Leaving directory `/home/ecerulm/tmp/pick/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ecerulm/tmp/pick'
make: *** [all] Error 2
```

I guess that the `freopen` call should be wrapped in an `assert()`
